pull_request_title: 'chore(strings): new translations'
files:
  - source: /en-US/*
    translation: /%locale%/%original_file_name%
    update_option: update_as_unapproved
  - source: /en-US/*
    translation: /%locale%/docs/%original_file_name%